"""add expense_date to cash_outflows

Revision ID: 60ab40229000
Revises: a48c036cee2c
Create Date: 2026-04-11 18:17:26.263034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ab40229000'
down_revision = 'a48c036cee2c'
branch_labels = None
depends_on = None


def upgrade():
    # Add as nullable first so existing rows don't violate NOT NULL
    with op.batch_alter_table('cash_outflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_date', sa.Date(), nullable=True))

    # Backfill from created_at converted to Africa/Lubumbashi local date
    op.execute("""
        UPDATE cash_outflows
        SET expense_date = (created_at AT TIME ZONE 'UTC' AT TIME ZONE 'Africa/Lubumbashi')::date
    """)

    # Enforce NOT NULL and add index
    with op.batch_alter_table('cash_outflows', schema=None) as batch_op:
        batch_op.alter_column('expense_date', nullable=False)
        batch_op.create_index(batch_op.f('ix_cash_outflows_expense_date'), ['expense_date'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_outflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_outflows_expense_date'))
        batch_op.drop_column('expense_date')

    # ### end Alembic commands ###
