"""add sale_date to sales

Revision ID: 6af45b709e68
Revises: 0df39880850f
Create Date: 2026-04-11 17:39:57.355435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af45b709e68'
down_revision = '0df39880850f'
branch_labels = None
depends_on = None


def upgrade():
    # Add as nullable first so existing rows don't violate the NOT NULL constraint
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_date', sa.Date(), nullable=True))

    # Backfill: derive sale_date from the created_at timestamp in Africa/Lubumbashi (UTC+2)
    op.execute("""
        UPDATE sales
        SET sale_date = (created_at AT TIME ZONE 'UTC' AT TIME ZONE 'Africa/Lubumbashi')::date
    """)

    # Now enforce NOT NULL and add the index
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('sale_date', nullable=False)
        batch_op.create_index(batch_op.f('ix_sales_sale_date'), ['sale_date'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_sale_date'))
        batch_op.drop_column('sale_date')

    # ### end Alembic commands ###
