"""Multi-tenant architecture

Revision ID: 8d3e0633f5f6
Revises:
Create Date: 2026-02-23 08:50:15.424797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3e0633f5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Drop any orphaned ENUM types left over from a partial/failed previous run
    # (e.g. tables were dropped manually but types were not).
    # Using CASCADE so any dependent columns are also handled.
    op.execute('DROP TYPE IF EXISTS roletype CASCADE')
    op.execute('DROP TYPE IF EXISTS cashoutflowcategory CASCADE')
    op.execute('DROP TYPE IF EXISTS networktype CASCADE')
    op.execute('DROP TYPE IF EXISTS cashinflowcategory CASCADE')

    # ### commands auto generated by Alembic ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'VENDEUR', 'STOCKEUR', name='roletype'), nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('cash_outflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('PURCHASE_AIRTIME', 'OPERATING_EXPENSE', 'SALARY', 'RENT', 'OTHER', name='cashoutflowcategory'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone_airtel', sa.String(length=20), nullable=True),
    sa.Column('phone_africel', sa.String(length=20), nullable=True),
    sa.Column('phone_orange', sa.String(length=20), nullable=True),
    sa.Column('phone_vodacom', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_long', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_overall_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_initial_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_purchased_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_sold_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_final_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_virtual_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_debts', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendeur_id', 'report_date', name='_vendeur_report_date_uc')
    )
    with op.batch_alter_table('daily_overall_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_overall_reports_report_date'), ['report_date'], unique=False)

    op.create_table('daily_stock_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('network', sa.Enum('AIRTEL', 'AFRICEL', 'ORANGE', 'VODACOM', name='networktype'), nullable=False),
    sa.Column('initial_stock_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchased_stock_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sold_stock_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_stock_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('virtual_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('debt_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendeur_id', 'report_date', 'network', name='_vendeur_report_date_network_uc')
    )
    with op.batch_alter_table('daily_stock_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_stock_reports_report_date'), ['report_date'], unique=False)

    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_codes_code'), ['code'], unique=True)

    op.create_table('stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.Enum('AIRTEL', 'AFRICEL', 'ORANGE', 'VODACOM', name='networktype'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('buying_price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendeur_id', 'network', name='_vendeur_network_uc')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_name_adhoc', sa.String(length=128), nullable=True),
    sa.Column('total_amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('debt_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchased_by_id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.Enum('AIRTEL', 'AFRICEL', 'ORANGE', 'VODACOM', name='networktype'), nullable=False),
    sa.Column('buying_price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_purchased', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['purchased_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_inflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('SALE_COLLECTION', 'OTHER', name='cashinflowcategory'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('network', sa.Enum('AIRTEL', 'AFRICEL', 'ORANGE', 'VODACOM', name='networktype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table('sale_items')
    op.drop_table('cash_inflows')
    op.drop_table('stock_purchases')
    op.drop_table('sales')
    op.drop_table('stock')
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_codes_code'))

    op.drop_table('invite_codes')
    with op.batch_alter_table('daily_stock_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_stock_reports_report_date'))

    op.drop_table('daily_stock_reports')
    with op.batch_alter_table('daily_overall_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_overall_reports_report_date'))

    op.drop_table('daily_overall_reports')
    op.drop_table('clients')
    op.drop_table('cash_outflows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    op.execute('DROP TYPE IF EXISTS roletype')
    op.execute('DROP TYPE IF EXISTS cashoutflowcategory')
    op.execute('DROP TYPE IF EXISTS networktype')
    op.execute('DROP TYPE IF EXISTS cashinflowcategory')
    # ### end Alembic commands ###
