"""add payment_date to cash_inflows

Revision ID: a48c036cee2c
Revises: 6af45b709e68
Create Date: 2026-04-11 18:01:01.683726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48c036cee2c'
down_revision = '6af45b709e68'
branch_labels = None
depends_on = None


def upgrade():
    # Add as nullable first so existing rows don't violate NOT NULL
    with op.batch_alter_table('cash_inflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=True))

    # Backfill from created_at converted to Africa/Lubumbashi local date
    op.execute("""
        UPDATE cash_inflows
        SET payment_date = (created_at AT TIME ZONE 'UTC' AT TIME ZONE 'Africa/Lubumbashi')::date
    """)

    # Enforce NOT NULL and add index
    with op.batch_alter_table('cash_inflows', schema=None) as batch_op:
        batch_op.alter_column('payment_date', nullable=False)
        batch_op.create_index(batch_op.f('ix_cash_inflows_payment_date'), ['payment_date'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_inflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_inflows_payment_date'))
        batch_op.drop_column('payment_date')

    # ### end Alembic commands ###
