"""add stock_opening_balances table

Revision ID: a97588386638
Revises: 60ab40229000
Create Date: 2026-04-19 13:37:27.086335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a97588386638'
down_revision = '60ab40229000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_opening_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendeur_id', sa.Integer(), nullable=False),
    sa.Column('network', postgresql.ENUM('AIRTEL', 'AFRICEL', 'ORANGE', 'VODACOM', name='networktype', create_type=False), nullable=False),
    sa.Column('balance_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('set_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendeur_id', 'network', 'balance_date', name='_opening_balance_vendeur_network_date_uc')
    )
    with op.batch_alter_table('stock_opening_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_opening_balances_balance_date'), ['balance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_opening_balances_vendeur_id'), ['vendeur_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_opening_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_opening_balances_vendeur_id'))
        batch_op.drop_index(batch_op.f('ix_stock_opening_balances_balance_date'))

    op.drop_table('stock_opening_balances')
    # ### end Alembic commands ###
