"""add api_token to users

Revision ID: d4b0b8e1bb3a
Revises: 0f711445b8f2
Create Date: 2026-06-21 10:37:34.383781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b0b8e1bb3a'
down_revision = '0f711445b8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_token'), ['api_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_token'))
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###
