"""Complete Sale-CashInflow relationship (SQLite compatible)

Revision ID: 50f194a3804e
Revises: c9889b74d2dc
Create Date: 2025-06-20 03:11:11.610929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f194a3804e'
down_revision = 'c9889b74d2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
