"""Remove reduction_rate_applied from SaleItem and reduction_rate from Stock

Revision ID: c9889b74d2dc
Revises: 2e07089eecc1
Create Date: 2025-06-18 16:02:48.182738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9889b74d2dc'
down_revision = '2e07089eecc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'reduction_rate_applied')
    op.drop_column('stock', 'reduction_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('reduction_rate', sa.NUMERIC(precision=5, scale=4), nullable=False))
    op.add_column('sale_items', sa.Column('reduction_rate_applied', sa.NUMERIC(precision=5, scale=4), nullable=False))
    # ### end Alembic commands ###
