"""Updated daily_report changing int and fload types to Numeric

Revision ID: efe550d73d72
Revises: 9f3bbb439280
Create Date: 2025-06-27 14:29:43.242892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe550d73d72'
down_revision = '9f3bbb439280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_overall_report')
    op.drop_table('daily_stock_report')
    op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('daily_stock_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_date', sa.DATE(), nullable=False),
    sa.Column('network', sa.VARCHAR(length=7), nullable=False),
    sa.Column('initial_stock_balance', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('purchased_stock_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('sold_stock_amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('final_stock_balance', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('virtual_value', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('debt_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date', 'network', name=op.f('_report_date_network_uc'))
    )
    op.create_table('daily_overall_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_date', sa.DATE(), nullable=False),
    sa.Column('total_initial_stock', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_purchased_stock', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_sold_stock', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_final_stock', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_virtual_value', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_debts', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_capital_circulant', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    # ### end Alembic commands ###
