"""Fix StockPurchase cost type hint

Revision ID: f05c42d85d69
Revises: 481e195d332f
Create Date: 2025-06-14 15:44:57.990625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05c42d85d69'
down_revision = '481e195d332f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
